[project]
name = "titan-forge"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ethan C"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[tasks]

[dependencies]
rattler-build = ">=0.34.1,<1"
