schema_version: 1

context:
  xorg_name: font-util
  xorg_category: font
  name: xorg-font-util
  version: 1.4.1
  sha256: 5c9f64123c194b150fee89049991687386e6ff36ef2af7b80ba53efaf368cc95
  am_version: 1.16

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://www.x.org/releases/individual/${{ xorg_category }}/${{ xorg_name }}-${{ version }}.tar.xz
  sha256: ${{ sha256 }}

build:
  number: 1

requirements:
  build:
    - if: win
      then: m2-autoconf
    - if: win
      then: m2-automake${{ am_version }}
    - if: win
      then: m2-libtool
    - if: unix
      then: pkg-config
    - if: win
      then: m2-pkg-config
    - if: win
      then: m2-base
    - if: unix
      then: make
    - if: win
      then: m2-make
    - if: unix
      then: ${{ compiler("c") }}
    - if: unix
      then: ${{ stdlib("c") }}
    - if: win
      then: ${{ compiler("m2w64_c") }}
    - if: win
      then: ${{ stdlib("m2w64_c") }}
  host:
    - xorg-util-macros

about:
  license: MIT
  license_file: COPYING
  summary: X.org font-related utilities.
  homepage: https://www.x.org/

extra:
  recipe-maintainers:
    - pkgw


