context:
  name: googletest
  version: 2024.11.20
  commit: 35d0c365609296fa4730d62057c487e3cfa030ff

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/google/googletest/archive/${{ commit }}.tar.gz
    sha256: 2bfa2a04c999741054f61f34ac43f8fce80458698aa385c52df15d762daf4cbd

build:
  number: 2
  script: build-googletest.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  run:
    - ${{ stdlib('c') }}

about:
  homepage: https://github.com/google/googletest
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Google testing and mocking framework

extra:
  recipe-maintainers:
    - ethanc8
